version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "433:433"
    networks:
      - internal
    volumes:
      # copy across the config as a synced volume so that we can edit it whilst running
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/index.html:/var/www/html/index.html
      - ./docker/nginx/logs:/var/log/nginx/

  wordpress1:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "10101:80"
    networks:
      - internal
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress1
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_PASSWORD=somewordpress
      - WORDPRESS_DEBUG=true
    volumes:
      - ./wordpress1:/var/www/html
      - ./docker/php/logs/php1.log:/var/log/fpm-php.www.log

  wordpress2:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "20202:80"
    networks:
      - internal
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress2
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_PASSWORD=somewordpress
      - WORDPRESS_DEBUG=true
    volumes:
      - ./wordpress2:/var/www/html
      - ./docker/php/logs/php2.log:/var/log/fpm-php.www.log

  wordpress3:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "30303:80"
    networks:
      - internal
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress3
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_PASSWORD=somewordpress
      - WORDPRESS_DEBUG=true
    volumes:
      - ./wordpress3:/var/www/html
      - ./docker/php/logs/php3.log:/var/log/fpm-php.www.log

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress1
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal
volumes:
  db_data:

networks:
  internal:
    driver: bridge